import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify'
import { Provider } from '@/components/ui/provider'
import NextTopLoader from 'nextjs-toploader'
import RefreshTokenProvider from '@/providers/RefreshTokenProvider'
import { colors } from '@/constants/themes'

const plusJakartaSans = Plus_Jakarta_Sans({
    variable: '--font-jakarta-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'NipponAuto',
    // description: 'Generated by create next app',
    // icons: {
    //     icon: '/truemoney-logo-black.png', // Path relative to the public directory
    //     shortcut: '/truemoney-logo-black.png',
    //     apple: '/truemoney-logo-black.png',
    //     other: {
    //         rel: 'apple-touch-icon-precomposed',
    //         url: '/truemoney-logo-black.png',
    //     },
    // },
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={plusJakartaSans.className}>
                <RefreshTokenProvider>
                    <Provider>
                        {/* <LoadingProvider>{children}</LoadingProvider> */}
                        <NextTopLoader
                            color={colors.tertiary}
                            initialPosition={0.08}
                            crawlSpeed={200}
                            height={3}
                            crawl={true}
                            showSpinner={true}
                            easing="ease"
                            speed={200}
                            shadow="0 0 10px #f2f3fa,0 0 5px #f2f3fa"
                            template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
                            zIndex={1600}
                            showAtBottom={false}
                        />
                        {children}
                    </Provider>
                </RefreshTokenProvider>

                <ToastContainer
                    position="bottom-right" // Position of the toast
                    autoClose={5000} // Duration before toast closes
                    hideProgressBar={true} // Show progress bar
                    closeOnClick // Close on click
                    pauseOnHover // Pause on hover
                />
            </body>
        </html>
    )
}
